// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyqcFl4-3xsRNMpL6-eu5hJEKye8N6-RI',
    appId: '1:285326205465:web:efc97b390d1fdb47d40088',
    messagingSenderId: '285326205465',
    projectId: 'itds283sec1gr15',
    authDomain: 'itds283sec1gr15.firebaseapp.com',
    storageBucket: 'itds283sec1gr15.firebasestorage.app',
    measurementId: 'G-6VY2J910VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOvVOaaopKuTKmTzLhCPG03FuVUSBAD_U',
    appId: '1:285326205465:android:876556b715e82df1d40088',
    messagingSenderId: '285326205465',
    projectId: 'itds283sec1gr15',
    storageBucket: 'itds283sec1gr15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sRRoEHxzllMoJ-OTE_XvA3rg9bTHYJA',
    appId: '1:285326205465:ios:c52942e861727a8ad40088',
    messagingSenderId: '285326205465',
    projectId: 'itds283sec1gr15',
    storageBucket: 'itds283sec1gr15.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sRRoEHxzllMoJ-OTE_XvA3rg9bTHYJA',
    appId: '1:285326205465:ios:c52942e861727a8ad40088',
    messagingSenderId: '285326205465',
    projectId: 'itds283sec1gr15',
    storageBucket: 'itds283sec1gr15.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyqcFl4-3xsRNMpL6-eu5hJEKye8N6-RI',
    appId: '1:285326205465:web:821f74a401bf4b4cd40088',
    messagingSenderId: '285326205465',
    projectId: 'itds283sec1gr15',
    authDomain: 'itds283sec1gr15.firebaseapp.com',
    storageBucket: 'itds283sec1gr15.firebasestorage.app',
    measurementId: 'G-BCNHLCYB3F',
  );
}
